### ISSUE TITLE
Nice, but...

### ISSUE THREAD

**Issue by chrispysaid** [meoiswa/TiltedPlugin#10]
Is all this plugin does is remember one camera setting, and trigger that one setting based on context? You can't have different camera presets for each situation? Am I just using it wrong? instructions are non-existent, and I'd really like a plugin that can change camera positions to different distances based on what I'm doing automatically. I thought this did that, but maybe not.

**Comment by meoiswa** [comment]
It can do that, yes, to an extent.
For what you describe, you'll want to use the Tweaks -> Camera Distance, set your "Enabled" and "Disabled" distances (you can set them by moving zooming in/out to the desired position, then presing the "Set" button for each, respectively).
Then you'll want to head into the Triggers section and enable whichever trigger works best for you, except the Zoomed one ofc (its mutually exclusive with the Camera Distance tweak).
I'll keep this ticket open to remind myself to add some explanation parragraphs to the different sections of the plugin.

**Comment by meoiswa** [comment]
![image](https://github.com/user-attachments/assets/0753bc9a-907e-484c-9ee8-ac5ce6e22975)
Here's an example of how to configure the plugin so that drawing your weapon pushes the zooms out the camera to the Enabled distance. Stowing your weapon brings the camera back to the Disabled distance
