### ISSUE TITLE
[Feature Request] Trigger - NPC Selected

### ISSUE THREAD

**Issue by Rellawing** [meoiswa/TiltedPlugin#7]
[Feature Request] Trigger - NPC Selected

It would be really cool if you added a NPC Selected condition. What this would do is allow us to zoom the camera in all the way while we have an NPC selected, creating the intimacy that many cutscenes have with an immersive UI.

I started using Tilted when I got a handheld system and started playing Final Fantasy 14 on it. Given the screen is smaller than a tv, the way it pans out when I'm in combat or mounted gives me a better view of everything around me. Whereas, I prefer to keep the camera a distance from over the shoulder for exploration. But the camera setting that I want to set for NPC conversations is not practical for adventuring.

This would benefit anyone that doesn't have a mouse wheel on their handheld. (I do, but it's bothersome to have to adjust it each time, IE: I get Tilted XD )

Thanks in advance if you choose to add this feature to your plugin!

**Comment by meoiswa** [comment]
For this to work the way you'd want, the plugin would need to be capable of having more than two camera setting states, which it will probably never support (too similar to Automation / Deciding for the player).
If you're already using it's in-combat trigger to zoom out/tilt up, you won't be able to also set the presumed "npc selected" trigger to zoom further in than your "off" state.
