### ISSUE TITLE
[Feature Request] Trigger - On Login

### ISSUE THREAD

**Issue by mo-pi** [meoiswa/TiltedPlugin#9]
I would like to just set my default zoom to the maximum so i don't have to zoom out every time I login.

**Comment by meoiswa** [comment]
You can achieve something very similar by setting the max value as both the Enabled and Disabled Camera Distance tweaks, and using an easy to trigger trigger such as the Weapon Sheathed trigger.
Doing things on behalf of the player on login is heavily frowned upon by PAC, as is any other action that triggers without player intervention.
The triggers that are currently implemented all rely on the player performing a specific action on their character (Joining a duty, engaging in combat with an enemy, unsheathing their weapon, etc.)
